### ISSUE TITLE
Bot Travando

### ISSUE THREAD

**Issue by Cortasso** [reegomes/Gaupoints-Farming#1]
Boa tarde, o bot está travando quando mandam uma sequência de emotes, mais em específico, emotes da live do Skipnho. Não sei se é um problema relacionado ao Windows 10, já que testei em 3 computadores e deu no mesmo erro. Poderia ver isso por gentileza? O mesmo problema ocorre nas lives Skipnholive e Skipnho. O mesmo problema está ocorrendo com os emotes do Gaules.
https://imgur.com/a/lQvBOYT (Imagem do bot travado)

**Comment by nazica** [comment]
Não é bug aparentemente.
A plataforma de pontos colocou um scan para pegar os bots.
Eu não estou ganhando mais pontos mesmo com o bot ligado e a live aberta.
Acabou o sonho :[

**Comment by nazica** [comment]
> Boa tarde, o bot está travando quando mandam uma sequência de emotes, mais em específico, emotes da live do Skipnho. Não sei se é um problema relacionado ao Windows 10, já que testei em 3 computadores e deu no mesmo erro. Poderia ver isso por gentileza? O mesmo problema ocorre nas lives Skipnholive e Skipnho. O mesmo problema está ocorrendo com os emotes do Gaules.
> https://imgur.com/a/lQvBOYT (Imagem do bot travado)

Não é bug aparentemente.
A plataforma de pontos colocou um scan para pegar os bots.
Eu não estou ganhando mais pontos mesmo com o bot ligado e a live aberta.
Acabou o sonho :[

**Comment by GabrielToth** [comment]
Estava vendo sobre farm na live do John e pelo jeito você precisa deixar a twitch em modo online, com o chat aberto, e ter mandado pelo menos 1 mensagem ali em quando vc entrou no chat deles. E a live não pode estar pausada nem mutada.

**Comment by RodrigoSecundo** [comment]
Galera eu ainda estou conseguindo farmar com esse esquema, sempre trava eu reseto, as vezes dura mais e as vezes dura menos. Porém vale a pena continuar usando.

**Comment by nazica** [comment]
> Galera eu ainda estou conseguindo farmar com esse esquema, sempre trava eu reseto, as vezes dura mais e as vezes dura menos. Porém vale a pena continuar usando.

Bom dia consagrado.
O problema não é estar ou não funcionando, mas sim que já estão identificando o uso dele na plataforma e banindo que usa.

**Comment by RodrigoSecundo** [comment]
@nazica Bom dia, já estou usando a mais de 1 mês, pra mim até agora nada de ban.

**Comment by rntsza** [comment]
Olá a todos, lembrem de seguir todos os passos do tutorial pra utilizar o bot.
Acabei de testar e continua funcionado, estou com ele aberto faz 3 horas e não travou (as vezes ele trava mesmo, mas ai é só abrir de novo).

Segue uma print: https://prnt.sc/129csfi
Estou encerrando essa issue.

**Comment by nazica** [comment]
Esta funcionando mas ja tem scan para detecta-lo.
Testei em duas lives e fui banido em uma.
Estou apenas informando ok?

**Comment by rntsza** [comment]
Estranho você ter tomado ban, se o bot não quebra nenhuma regra da Twitch.
E se você tomou ban em uma, deveria ter tomado nas duas, mas tudo bem né.
É só não usar mais então.

**Comment by nazica** [comment]
Querido, bom dia.
Não estou aqui para criticar a eficácia do seu bot. Ele é ótimo e funciona, mas esta sendo detectado por ferramentas de scan do streamer Skipinho.
O BAN não é da Twitch, mas do sistema de pontos do stream. Se for pego é BAN Permanente e nunca mais vai farmar pontos na live dele.
Estou informando apenas que o moderador dele esta identificando o bot, banindo e travando quem usa no sistema da loja de pontos.
Acabei de testar na outra life e tb já foi identificado e não ganho mais pontos.
Estou apenas informando o que aconteceu comigo e com mais uma galera na live dele. É só entrar na live dele e perguntar sobre a BAN wave que vão te responder ok?
Eu não perdi nada com isso, mas tem gente que pode ter muito mais a perder que eu por la.
Ótimo dia para você e fique em paz, estou apenas reportando o problema para os usuários do BOT estarem cientes que pode acontecer o mesmo com eles.
SS da ultima tentativa de farm.
[https://imgur.com/LFNTjIf](url)
