### ISSUE TITLE
entrando no chat do gaules em vez do que eu quero

### ISSUE THREAD

**Issue by wefghjk** [reegomes/Gaupoints-Farming#3]
mesmo editando o gaupoints.exe.config entra no chat como um reegomes

a config ta assim: 

<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <configSections>
        
        <section name="entityFramework" type="System.Data.Entity.Internal.ConfigFile.EntityFrameworkSection, EntityFramework, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" requirePermission="false" />
    <sectionGroup name="userSettings" type="System.Configuration.UserSettingsGroup, System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" >
      <section name="Sentinel.Config" type="System.Configuration.ClientSettingsSection, System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" allowExeDefinition="MachineToLocalUser" requirePermission="false" />
      <section name="GauPoints.Config" type="System.Configuration.ClientSettingsSection, System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" allowExeDefinition="MachineToLocalUser" requirePermission="false" />
    </sectionGroup>
    </configSections>
  <connectionStrings>
    <add name="ContextDB" connectionString="data source=.\SQLEXPRESS;Integrated Security=SSPI;Initial Catalog=ContextDB" providerName="System.Data.SqlClient" />
  </connectionStrings>
    <startup> 
        <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.7.2" />
    </startup>
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.Extensions.Logging.Abstractions" publicKeyToken="adb9793829ddae60" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-2.1.1.0" newVersion="2.1.1.0" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
  <entityFramework>
    <providers>
      <provider invariantName="System.Data.SqlClient" type="System.Data.Entity.SqlServer.SqlProviderServices, EntityFramework.SqlServer" />
    </providers>
  </entityFramework>
  <userSettings>
    <GauPoints.Config>
      <setting name="nao sou demente de mostrar" serializeAs="String">
        <value>Token what was generated on Twitch</value>
      </setting>
      <setting name="big_shaq10000" serializeAs="String">
        <value>Name of your bot(your user)</value>
      </setting>
      <setting name="cachorro1337c" serializeAs="String">
        <value>Name of channel what you want to ~watch~</value>
      </setting>
      <setting name="ClientID" serializeAs="String">
        <value>ClientID what was generated on Twitch</value>
      </setting>
    </GauPoints.Config>
  </userSettings>
</configuration>

**Comment by rntsza** [comment]
🤦🏻‍♂️

**Comment by rntsza** [comment]
Releia o tutorial, abraços.
