### ISSUE TITLE
mesmo problema

### ISSUE THREAD

**Issue by wefghjk** [reegomes/Gaupoints-Farming#4]
acho que o texto do config não tava inteiro por ser grande e não posso responder voce de volta por voce ter fechado  o artigo, mas eu coloquei meu token de acesso, nome do meu usuario e o streamer que eu queria que no caso é o cachorro1337c, mesmo com essas coisas e salvando o arquivo aconteceu aquilo

**Comment by rntsza** [comment]
Releia novamente com atenção. =)
